"""Create Search Vector

Revision ID: de236a0f1802
Revises: 9039d18350eb
Create Date: 2026-02-19 21:05:03.436406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de236a0f1802'
down_revision: Union[str, Sequence[str], None] = '9039d18350eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("\n            setweight(to_tsvector('english', coalesce(name, '')), 'A')\n            || \n            setweight(to_tsvector('english', coalesce(description, '')), 'B')\n            ", persisted=True), nullable=False))
    op.create_index('ix_products_tsv_gin', 'products', ['tsv'], unique=False, postgresql_using='gin')
    op.drop_column('products', 'rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_index('ix_products_tsv_gin', table_name='products', postgresql_using='gin')
    op.drop_column('products', 'tsv')
    # ### end Alembic commands ###
